### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by EasonWang01** [jcreamer898/expressiso#1]
Do you know how to automatic update page when server update?

**Comment by fa7ad** [comment]
Go to this [link](http://andrewhfarmer.com/starter-project/) and find a starter project with **HMR**. There's too many already with HMR and kinda fancy stuff, I use this primarily because it doesn't have all the bells and whistles

**Comment by tymekg** [comment]
@EasonWang01 Oh man.. I'm sure you could really come up with a better (i.e. more descriptive) title for the issue than "Hi"

**Comment by EasonWang01** [comment]
Not sure why I just type Hi one years ago = =.
